### ISSUE TITLE
桶装火箭燃料点不出来

### ISSUE THREAD

**Issue by Hundredmeters** [wenjianQL/GameCalculator#3]
桶装火箭燃料点不出来诶，是还没更新配方吗，我看别的都能点出来
![2024-10-25_09-23](https://github.com/user-attachments/assets/db682b53-d09b-4e9b-817b-1817dd33d3b2)

**Comment by wenjianQL** [comment]
已修改。编号：e62d7bd5

**Comment by wenjianQL** [comment]
已修改。编号：e62d7bd5
